server:
  port: 31001
spring:
  application:
    name: xc-service-cms
  data:
    mongodb:
      uri: mongodb://root:root@192.168.110.173:27017
      database: xc_cms

  freemarker:
    cache: false

  rabbitmq:
    host: 192.168.110.173
    username: leyou
    password: leyou
    virtual-host: /leyou

